### ISSUE TITLE
`flutter_map` 2.0.0 dependency mismatch

### ISSUE THREAD

**Issue by aytunch** [lpongetti/flutter_map_marker_cluster#126]
> Running "flutter pub get" in video_tutorial...                  
> Because flutter_map_marker_cluster 0.5.0 depends on flutter_map ^1.0.0 and no versions of flutter_map_marker_cluster match >0.5.0 <0.6.0, flutter_map_marker_cluster ^0.5.0 requires flutter_map ^1.0.0.
> So, because bare_bones depends on both flutter_map ^2.0.0 and flutter_map_marker_cluster ^0.5.0, version solving failed.
> pub get failed (1; So, because bare_bones depends on both flutter_map ^2.0.0 and flutter_map_marker_cluster ^0.5.0, version solving failed.)
> exit code 1

The only way to run is to add;

```
dependency_overrides:
  flutter_map: ^2.0.0
```

**Comment by Vafin84** [comment]
When will the next version of the package be released?

**Comment by aytunch** [comment]
@Vafin84 for the time being, you can use
```
  flutter_map: ^2.0.0
  flutter_map_marker_cluster:
    git:
      url: https://github.com/aytunch/flutter_map_marker_cluster
```
