### ISSUE TITLE
Depndendecy on old flutter_map

### ISSUE THREAD

**Issue by MichalMisiaszek** [lpongetti/flutter_map_marker_cluster#13]
Because flutter_map_marker_cluster >=0.1.3 depends on flutter_map ^0.5.5+2 and <my app> depends on flutter_map ^0.6.1+2, flutter_map_marker_cluster >=0.1.3 is forbidden.

So, because pest_scope depends on flutter_map_marker_cluster ^0.2.0+1, version solving failed.

**Comment by lpongetti** [comment]
flutter_map ^0.6.1+2 is broken and it is for flutter channel dev...
for use flutter_map and flutter_map_marker_cluster in channel != stable:

```yaml
  flutter_map:
    git:
      url: https://github.com/johnpryan/flutter_map.git
      ref: dev
  flutter_map_marker_cluster:
    git:
      url: https://github.com/lpongetti/flutter_map_marker_cluster.git
      ref: develop
```
