### ISSUE TITLE
New Flutter_Map Version released (incompatible)

### ISSUE THREAD

**Issue by moritzdawo** [lpongetti/flutter_map_marker_cluster#165]
Flutter Map 4.0.0 was released, but Flutter Map Marker Cluster needs any Map version below.
Please update your plugin for compatibility.
Thank you!

**Comment by xDefcon** [comment]
Related PR: https://github.com/lpongetti/flutter_map_marker_cluster/pull/164

**Comment by caini1213** [comment]
Yup, will need it to compatible with Flutter Map 4.0.0.
Thanks

**Comment by nploi** [comment]
> Yup, will need it to compatible with Flutter Map 4.0.0. Thanks

Hi @caini1213, You can use my fork first.
```
  flutter_map_marker_cluster:
    git:
      url: https://github.com/nploi/flutter_map_marker_cluster
      ref: upgrade_flutter_map_v4
```
