### ISSUE TITLE
Upgrade to latest flutter map 1.10.1

### ISSUE THREAD

**Issue by fryette** [lpongetti/flutter_map_marker_cluster#46]

**Comment by pinzon** [comment]
Any news when are we gonna be able to use it?

**Comment by fvisticot** [comment]
Any news on this issue ?

**Comment by pinzon** [comment]
No, there is a pull request that is supposed to fix that, but it hasn't been implemented

**Comment by fryette** [comment]
For now, have a reference on @Xennis PR in my flutter app
Thx!

**Comment by palicka** [comment]
In case, someone don't know how to do it:

```
  flutter_map_marker_cluster:
    git:
      url: https://github.com/Xennis/flutter_map_marker_cluster.git
      ref: fluttermap-10
```
