### ISSUE TITLE
Update flutter_map dependencies

### ISSUE THREAD

**Issue by tsdevelopment** [lpongetti/flutter_map_marker_cluster#9]
Please update flutter_map dependencies to `^0.6.1+2` - otherwise it's not useable with latest version of `flutter_map`.

**Comment by lpongetti** [comment]
Flutter_map 0.6.1+2 doesnt work. You have to reference flutter_map git url branch dev and flutter_map_marker_cluster git url branch develop

```yaml
  flutter_map:
    git:
      url: https://github.com/johnpryan/flutter_map.git
      ref: dev
  flutter_map_marker_cluster:
    git:
      url: https://github.com/lpongetti/flutter_map_marker_cluster.git
      ref: develop
```
